<?php

defined( 'ABSPATH' ) || exit;

    //options tab
$sitemap_file = LS_CRAWLER_STATS_FOLDER_PATH.'sitemap-cache.log';
?>
<h3><?=__('Options','ls_crawler')?></h3>
<?php

if ( is_crawler_running() ) {
    ?>
    <b>Crawler now running, you can't change the settings now</b><br><br>
    <?php
}

?>
    <form method="POST" action="options-general.php?page=ls_cache_crawler&tab=options" _lpchecked="1" autocomplete="off" >
    <input type="hidden" name="page" value="ls_cache_crawler">
    <input type="hidden" name="tab" value="options">
    <div class="tab-box">
        <span class="tab-left">Query string to bypass CDN:</span> 
        <input type="text" placeholder="" autocomplete="off" name="bypass-qs" <?php the_form_value($crawler_settings['bypass-qs'])?> >
        <span class= "exp-text">e.g. <i>wp-admin</i>  Will be always addedd to the crawled URL</span>
    </div>
    <div class="tab-box">
        <span class="tab-left">Secondary query string:</span> 
        <input type="text" placeholder="" autocomplete="off" name="second-qs" <?php the_form_value($crawler_settings['second-qs'])?> >
        <span class= "exp-text">e.g. <i>wcmlc=EUR,lang=es</i> for two separate or <i>wcmlc=EUR&lang=es</i> for one compound query string. Makes extra scan for each query string.</span>
    </div>
    <div class="tab-box">
        <span class="tab-left">Whitelist IP:</span> 
        <input type="text" placeholder="" autocomplete="off" name="whitelist-ip" <?php the_form_value($crawler_settings['whitelist-ip'])?> >
        <span class= "exp-text">IP where your cron will come from, default allows server's IP and IPs of <a href="https://www.easycron.com/" target="_blank">Easycron</a></span>
    </div>
    <div class="tab-box">
        <span class="tab-left">Exclude keywords:</span> 
        <input type="text" placeholder="" autocomplete="off" name="excluded-keyword" <?php the_form_value($crawler_settings['excluded-keyword'])?> >
        <span class= "exp-text">separated by coma e.g. <i>shop,blog,tag</i></span>
    </div>
    <div class="tab-box">
        <span class="tab-left">Custom sitemap URL:</span> 
        <input type="text" placeholder="" autocomplete="off" name="secondary-sitemap" <?php the_form_value($crawler_settings['secondary-sitemap'])?>>
        <span class= "exp-text">e.g. <i>/sitemap.xml</i></span>
    </div>
    <div class="tab-box">
        <span class="tab-left">Slow down crawl when server load is over:</span> 
        <input type="number" placeholder="Default is 3" autocomplete="off" name="max-server-load" <?php the_form_value($crawler_settings['max-server-load'])?> >
        <span class= "exp-text">When server load reach this level, it will increase time between individual requests to 500ms, default is 100ms, 0 is no delay between crawler's request. Current: <?=get_current_server_load_lsc()?></span>
    </div>
    <div class="tab-box">
        <span class="tab-left">Add Mobile user agent</span>
        <span class="chkbox-wrap"> <input type="checkbox" placeholder="" name="mobile" value="1" <?php the_form_checked($crawler_settings['mobile'])?> class="chkbox" ></span>
        <span class= "exp-text">Will make another request with added mobile user agent</span>
    </div>
    <?php
    if ( !is_crawler_running() ) {
    ?>
    <button class="button button-primary" type="submit" id="submit">Save settings</button>
    <?php 
    }
    ?>
</form>
<br><br>
In order to crawler run, you have to have sitemap generated by SEO plugin. Default url is <?=get_home_url(); ?>/sitemap_index.xml<br>
If your sitemap is not on this url, please add your sitemap url to secondary sitemap setting field.<br> 
Sitemap TTL is 24 hours. Purge if you just added pages and they not have been crawled. 
<br><br>
<form method="GET" action="options-general.php" _lpchecked="1">
<input type="hidden" name="page" value="ls_cache_crawler">
<input type="hidden" name="tab" value="options">
<input type="hidden" name="purge">
<?php

    if ( isset($_GET['purge']) && !is_crawler_running() && file_exists($sitemap_file) ){

        unlink($sitemap_file);
    } 

    if ( !is_crawler_running() && file_exists($sitemap_file) ) {
    ?>
    <button class="button button-primary" type="submit" id="submit">Purge sitemap cache</button>
    </form>
    <?php
    }

    $cdn_qs = empty($crawler_settings['bypass-qs']) ? '' : '?'.$crawler_settings['bypass-qs'];
    
    $crawler_url_with_cdn_qs =  LS_CRAWLER_URL.$cdn_qs;

    ?>
    <br><br>
    <div class="tab-box">
    <span class="tab-left">For <a href="https://www.easycron.com/" target="_blank">Easycron</a> link is:</span>
        <input id="copytextarea1" type="text" size="90" value="<?php echo $crawler_url_with_cdn_qs ?>" /> 
        <button id="copyTextBtn1" class="button button-primary">Copy</button>
    </div>
    <div class="tab-box">
    <span class="tab-left">The link for cron job in Cpanel/Plesk:</span>
        <input id="copytextarea2" type="text" size="90" value="curl <?php echo $crawler_url_with_cdn_qs ?> >/dev/null 2>&1" />
        <button id="copyTextBtn2" class="button button-primary">Copy</button>
    </div>

<script>
copyTextBtn1 = document.querySelector('#copyTextBtn1');
    copyTextBtn1.addEventListener('click', function(event) {
    let copytextarea1 = document.querySelector('#copytextarea1');
    copytextarea1.focus();
    copytextarea1.select();
    try {
        let successful = document.execCommand('copy');
        let msg = successful ? 'successful' : 'unsuccessful';
    } catch(err) {
        
    }
    });

copyTextBtn2 = document.querySelector('#copyTextBtn2');
copyTextBtn2.addEventListener('click', function(event) {
let copytextarea2 = document.querySelector('#copytextarea2');
copytextarea2.focus();
copytextarea2.select();
try {
let successful = document.execCommand('copy');
let msg = successful ? 'successful' : 'unsuccessful';
} catch(err) {

}
});
</script>
    
<?php

